// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awomuthefgenqgccngfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3b211dGhlZmdlbnFnY2NuZ2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzUzODQsImV4cCI6MjA2MTUxMTM4NH0.vf8IEg2DHJ17Brh3bvmFpCAyE6hE3NT455Ovdc2hW3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);